In [1]:
import pandas as pd

In [2]:
import random

In [3]:
# 1. Definimos la cantidad de filas deseadas (1 millón)
cantidad = 1000000

In [4]:
# 2. Conjunto de datos base reales/coherentes para la simulación de Cancún
influencers_pool = ["@travel_cancun", "@beach_vibe", "@mexico_explorers", "@lifestyle_blogger", "@paradise_seek", "@cancun_sunsets"]
tipos_post_pool = ["foto", "video", "reel", "carrusel"]
fechas_pool = ["2026-05-01", "2026-05-10", "2026-05-15", "2026-05-20", "2026-05-24"]

In [5]:
# 3. Creación del DataFrame de 1,000,000 de registros usando comprensión de listas
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers_pool) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],       # Rango de likes realista
    "comentarios": [random.randint(5, 2500) for _ in range(cantidad)],    # Rango de comentarios realista
    "fecha": [random.choice(fechas_pool) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post_pool) for _ in range(cantidad)]
})

In [6]:
# Definimos la cantidad (1 millón de registros)
cantidad = 1000000

In [7]:
df_instagram.shape

(1000000, 5)

In [8]:
df_instagram.dtypes

influencer       str
likes          int64
comentarios    int64
fecha            str
tipo_post        str
dtype: object

In [9]:
df_instagram.head()

           influencer  likes  comentarios       fecha tipo_post
0      @travel_cancun  14692          281  2026-05-10     video
1  @lifestyle_blogger  29894         2018  2026-05-20      reel
2         @beach_vibe  11311         1427  2026-05-24      reel
3      @travel_cancun  44225          374  2026-05-01      reel
4         @beach_vibe  47313         2259  2026-05-24      reel

In [10]:
df_instagram.memory_usage(deep=True).sum() / (1024**2)

np.float64(184.1372127532959)

In [11]:
print("Promedio de Likes:", df_instagram["likes"].mean())
print("Promedio de Comentarios:", df_instagram["comentarios"].mean())

Promedio de Likes: 25029.390267
Promedio de Comentarios: 1251.873097

In [12]:
df_instagram.groupby("tipo_post")[["likes", "comentarios"]].mean()

                  likes  comentarios
tipo_post
carrusel   25043.152352  1252.446371
foto       25030.952159  1252.841863
reel       24996.587275  1250.740441
video      25046.828795  1251.463994

In [13]:
df_instagram.groupby("influencer")["likes"].sum().sort_values(ascending=False)

influencer
@beach_vibe           4192306739
@travel_cancun        4178055073
@cancun_sunsets       4172465112
@lifestyle_blogger    4164152704
@paradise_seek        4161255805
@mexico_explorers     4161154834
Name: likes, dtype: int64