# Preprocesamiento de los datos de Maching Learning
Aplicar las tecnicas principales de preprocesamiento de datos para recuperar un datasetantes del entrenamiento

## Parte 1. Comprensión del problema

Trabajeremos con el Dataset de Titanic, para construir un modelo que sea capaz de
predecir si una persona sobrevive o no.

In [23]:
import pandas as pd
import numpy as np

#Librerias de Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler  # <- ¡Asegúrate de que tenga la 'd'!
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

#Librerias para graficar
import seaborn as sns
import matplotlib.pyplot as plt

#Libreria de Kaggle
import kagglehub

In [24]:
import os

# 1. Descargar el dataset del Titanic desde Kaggle
path = kagglehub.dataset_download("rahulsah06/titanic")
print("El dataset se descargó en:", path)

# 2. Cargar el archivo de entrenamiento (train.csv)
df = pd.read_csv(os.path.join(path, "train.csv"))

# 3. Mostrar las primeras 5 filas para comprobar que todo esté en orden
df.head()

El dataset se descargó en: C:\Users\100043016\.cache\kagglehub\datasets\rahulsah06\titanic\versions\1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
# descargamos el dataset de la pagina kaggle
# Descargamos el Dataset de la pagina Kaggle
path = kagglehub.dataset_download("yasserh/titanic-dataset")
path  # Imprimimos la ruta

'C:\\Users\\100043016\\.cache\\kagglehub\\datasets\\yasserh\\titanic-dataset\\versions\\1'

In [26]:
# Creamos el Dataframe
dfTitanic = pd.read_csv(path + "/Titanic-Dataset.csv")

In [27]:
# Mostramos las primeras 5 filas
dfTitanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
dfTitanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# Parte 2 Seleccion de Variables Predictoras y la Variable Objetivo
La variable objetivo sera: survived
donde 0 = No sobrevivio 1 = sobrevivio

In [29]:
dfTitanic["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [30]:
dfTitanic.groupby(
    "Sex"
)["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [31]:
dfTitanic.groupby(
    "Pclass"
)["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [32]:
dfTitanic.groupby(
    "Fare"
)["Survived"].mean()

Fare
0.0000      0.066667
4.0125      0.000000
5.0000      0.000000
6.2375      0.000000
6.4375      0.000000
              ...
227.5250    0.750000
247.5208    0.500000
262.3750    1.000000
263.0000    0.500000
512.3292    1.000000
Name: Survived, Length: 248, dtype: float64

## Parte 3. Correlacion e Hipotesis
Vamos a identificar la relacion entre variables numericas.
nota: la correlacion NO representa la importancia REAL de la variable en el modelo

In [33]:
variables_numericas = [
    "Survived",
    "Pclass",
    "SibSp",
    "Age"
    "Parch",
    "Fare"
]

In [34]:
# Creamos la matriz de correlación
corr = dfTitanic[variables_numericas].corr() #Creamos la matriz de correlacion
corr

KeyError: "['AgeParch'] not in index"

In [35]:
plt.figure(figsize=(8,6))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm"
)
plt.title("Matriz de correlación")
plt.show()

NameError: name 'corr' is not defined

## Parte 4. Variables Predictoras

X --> Aquellas variables que nos ayudan a predecir
Y --> Variable Objetivo

In [36]:
dfTitanic.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [37]:
# 2. Asignamos las variables independientes a X y la variable objetivo a y
X = dfTitanic[columnas]
y = dfTitanic["Survived"]

NameError: name 'columnas' is not defined

In [38]:
# 1. Definimos la lista de columnas numéricas que usaremos como características (Features)
columnas = ["Pclass", "SibSp", "Parch", "Age", "Fare"]

In [39]:
y.name #Objetivo

'Survived'

## Parte 5. Limpieza de datos

Realizaremos la imputacion de los datos, donde existan valores nulos.

In [40]:
X.isnull().sum()

NameError: name 'X' is not defined

In [41]:
# Rellenamos los nulos de la edad con la mediana directamente en el dataset original
dfTitanic["Age"] = dfTitanic["Age"].fillna(dfTitanic["Age"].median())

# Verificamos rápidamente que ya no haya nulos en 'Age'
print("Nulos en Age:", dfTitanic["Age"].isnull().sum())

Nulos en Age: 0

In [42]:
# Incluimos 'Age' dentro de las características para el modelo
columnas = ["Pclass", "Age", "SibSp", "Parch", "Fare"]

# Volvemos a definir X e y con la columna integrada
X = dfTitanic[columnas]
y = dfTitanic["Survived"]

# Comprobamos las dimensiones
print(f"Nuevas dimensiones de X: {X.shape}")

Nuevas dimensiones de X: (891, 5)

In [43]:
# Vamos a imputar los datos para el campo Edad, calculando la mediana en el DataFrame original
dfTitanic["Age"] = dfTitanic["Age"].fillna(dfTitanic["Age"].median())

In [44]:
# Vamos a imputar los datos para el campo Embarked, calculando la moda en el DataFrame original
dfTitanic["Embarked"] = dfTitanic["Embarked"].fillna(dfTitanic["Embarked"].mode()[0])

In [45]:
# Validamos rápidamente que ya no queden valores nulos en estas columnas
print("Nulos en Age:", dfTitanic["Age"].isnull().sum())
print("Nulos en Embarked:", dfTitanic["Embarked"].isnull().sum())

Nulos en Age: 0
Nulos en Embarked: 0

# Parte 6 normalizamos los datos categoricos (texto)
los algoritmos de ML no entienden texto

In [46]:
X.head(2)

   Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833

In [47]:
# Definimos las columnas originales que queremos (incluyendo las de texto)
columnas_totales = ["Pclass", "Sex", "Age", "Fare", "Embarked"]

In [48]:
# Reiniciamos la variable X tomándolas del DataFrame original limpio
X = dfTitanic[columnas_totales]

In [49]:
# Aplicamos el One-Hot Encoding
X = pd.get_dummies(
    X,
    columns=[
        "Sex",
        "Embarked"
    ],
    drop_first=True
)

In [50]:
X.head(2)

   Pclass   Age     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  22.0   7.2500      True       False        True
1       1  38.0  71.2833     False       False       False

# Parte 7. Division de los datos
no debemos entrenar y evaluar utilizando los mismos datos
80% para entrenar
20% para evaluar

In [78]:

# 2. Dividimos el dataset en conjuntos de entrenamiento (Train) y prueba (Test)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [79]:
y = dfTitanic["Survived"]

In [80]:
# [29]: Imprimir las dimensiones del conjunto de entrenamiento X
print("Entrenamiento X: ", X_train.shape)

# [30]: Imprimir las dimensiones del conjunto de prueba X
print("Prueba X: ", X_test.shape)

# [31]: Imprimir las dimensiones del conjunto de entrenamiento Y
print("Entrenamiento Y: ", y_train.shape)

# [32]: Imprimir las dimensiones del conjunto de prueba Y
print("Prueba Y: ", y_test.shape)

Entrenamiento X:  (712, 6)
Prueba X:  (179, 6)
Entrenamiento Y:  (712,)
Prueba Y:  (179,)

## Escalado de los datos
Las variables numericas tienen valores distintos. El escalado evita que las variables con mayores valores dominen el aprendizaje del modelo

In [81]:
columnas_numericas = [
    "Age",
    "Fare",
]

In [82]:
X_train[columnas_numericas].describe()

              Age        Fare
count  712.000000  712.000000
mean    29.204129   32.586276
std     13.007971   51.969529
min      0.420000    0.000000
25%     22.000000    7.925000
50%     28.000000   14.454200
75%     35.000000   30.500000
max     80.000000  512.329200

In [83]:
# Escalamos los datos usando StandarScaler
scaler = StandardScaler()

In [84]:
X_train[columnas_numericas] = scaler.fit_transform(X_train[columnas_numericas])
X_test[columnas_numericas] = scaler.fit(X_test[columnas_numericas])

In [85]:
X_train[columnas_numericas].describe()

                Age          Fare
count  7.120000e+02  7.120000e+02
mean   1.746418e-17  5.363999e-17
std    1.000703e+00  1.000703e+00
min   -2.214363e+00 -6.274674e-01
25%   -5.542135e-01 -4.748670e-01
50%   -9.263364e-02 -3.491435e-01
75%    4.458762e-01 -4.017244e-02
max    3.907725e+00  9.237724e+00

# Entrenamiento de algoritmo: Arbol de decision

Permite clasificar los registros con respecto a las variables

In [86]:
modelo = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

In [87]:
modelo.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

# Evaluamos la eficacia del modelo

Realizamos predicciones sobre el conjunto de prueba, para calcular la exactitud del modelo

In [88]:
# 1. Creamos el escalador
scaler = StandardScaler()

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [91]:
scaler = StandardScaler()

# Entrenamiento: Ajusta y transforma
X_train[columnas_numericas] = scaler.fit_transform(X_train[columnas_numericas])

# Prueba: SOLO transforma (¡Sin el .fit()!)
X_test[columnas_numericas] = scaler.transform(X_test[columnas_numericas])

In [92]:
# Volvemos a entrenar el modelo con los datos bien escalados
modelo.fit(X_train, y_train)

# Ahora la predicción ya no fallará
prediccion = modelo.predict(X_test)

In [93]:
pd.DataFrame(
    {
        "Survived Real: ": y_test,
        "Survived Predicha: ": prediccion
    }
).head(20)

     Survived Real:   Survived Predicha:
709                1                    0
439                0                    0
840                0                    0
720                1                    1
39                 1                    1
290                1                    1
300                1                    1
333                0                    0
208                1                    1
136                1                    1
137                0                    0
696                0                    0
485                0                    0
244                0                    0
344                0                    0
853                1                    1
621                1                    0
653                1                    1
886                0                    0
110                0                    0

## Evaluacion del modelo

Utilizaremos el accuracy para determinar el porcentaje de predicciones correctas realizadas por el modelo.

In [94]:
accuracy = accuracy_score(y_test, prediccion)

In [95]:
print(f"La exactitud del modelo es: {accuracy:.4f}")

La exactitud del modelo es: 0.7989

In [96]:
from sklearn.metrics import classification_report

In [97]:
print(classification_report(y_test, prediccion))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84       105
           1       0.84      0.64      0.72        74

    accuracy                           0.80       179
   macro avg       0.81      0.77      0.78       179
weighted avg       0.80      0.80      0.79       179